import {
  Play,
  Square,
  Code2,
  Globe,
  GitBranch,
  Repeat,
  RefreshCw,
  Clock,
  type LucideIcon,
} from 'lucide-react'
import {
  LOOP_BODY_WORK_NODE_TYPES,
  WORKFLOW_NODE_META,
  formatWorkflowNodeTypeLabel,
  getWorkflowNodeLabel,
  getWorkflowNodeTypeOrdinals,
  isAutoGeneratedWorkflowLabel,
  isLoopBodyWorkNodeType,
  isTestFlowNodeType,
  resolveWorkflowNodeDisplayLabel,
  type TestFlowNodeType,
} from '@/lib/test-flow-graph'

export interface WorkflowNodeDefinition {
  type: TestFlowNodeType
  label: string
  description: string
  icon: LucideIcon
}

const iconByType: Record<TestFlowNodeType, LucideIcon> = {
  start: Play,
  end: Square,
  script: Code2,
  'api-call': Globe,
  'if-else': GitBranch,
  'for-loop': Repeat,
  'do-while': RefreshCw,
  wait: Clock,
}

export const WORKFLOW_NODE_DEFINITIONS: WorkflowNodeDefinition[] = WORKFLOW_NODE_META.map(
  (definition) => ({
    ...definition,
    icon: iconByType[definition.type],
  }),
)

export const getLoopBodyWorkNodeDefinitions = (): WorkflowNodeDefinition[] => {
  return WORKFLOW_NODE_DEFINITIONS.filter((def) => isLoopBodyWorkNodeType(def.type))
}

export {
  formatWorkflowNodeTypeLabel,
  getWorkflowNodeLabel,
  getWorkflowNodeTypeOrdinals,
  isAutoGeneratedWorkflowLabel,
  isLoopBodyWorkNodeType,
  isTestFlowNodeType,
  resolveWorkflowNodeDisplayLabel,
}
