import {
  Play,
  Square,
  Code2,
  Globe,
  GitBranch,
  Repeat,
  RefreshCw,
  Clock,
  type LucideIcon,
} from 'lucide-react'
import type { TestFlowNodeType } from '@/lib/test-flow-graph'

export interface WorkflowNodeDefinition {
  type: TestFlowNodeType
  label: string
  description: string
  icon: LucideIcon
}

export const WORKFLOW_NODE_DEFINITIONS: WorkflowNodeDefinition[] = [
  { type: 'start', label: 'Start', description: 'Flow entry point', icon: Play },
  { type: 'end', label: 'End', description: 'Flow exit point', icon: Square },
  { type: 'script', label: 'Script', description: 'Run custom code', icon: Code2 },
  { type: 'api-call', label: 'API Call', description: 'HTTP request step', icon: Globe },
  { type: 'if-else', label: 'If / Else', description: 'Conditional branch', icon: GitBranch },
  { type: 'for-loop', label: 'For Loop', description: 'Iterate a fixed count', icon: Repeat },
  { type: 'do-while', label: 'Do While', description: 'Loop until condition', icon: RefreshCw },
  { type: 'wait', label: 'Wait', description: 'Pause execution', icon: Clock },
]

/** Work node types that can be placed inside a loop body (including nested loops). */
export const LOOP_BODY_WORK_NODE_TYPES: TestFlowNodeType[] = [
  'script',
  'api-call',
  'wait',
  'if-else',
  'for-loop',
  'do-while',
]

export function isLoopBodyWorkNodeType(nodeType: TestFlowNodeType): boolean {
  return LOOP_BODY_WORK_NODE_TYPES.includes(nodeType)
}

export function getLoopBodyWorkNodeDefinitions(): WorkflowNodeDefinition[] {
  return WORKFLOW_NODE_DEFINITIONS.filter((def) => isLoopBodyWorkNodeType(def.type))
}

export function isTestFlowNodeType(value: string): value is TestFlowNodeType {
  return WORKFLOW_NODE_DEFINITIONS.some((def) => def.type === value)
}

export function getWorkflowNodeLabel(nodeType: TestFlowNodeType): string {
  return WORKFLOW_NODE_DEFINITIONS.find((def) => def.type === nodeType)?.label ?? nodeType
}

function escapeRegExp(value: string): string {
  return value.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')
}

/** True when label is empty or matches the default type label (optional " N" suffix). */
export function isAutoGeneratedWorkflowLabel(
  label: string | undefined,
  nodeType: TestFlowNodeType,
): boolean {
  const trimmed = label?.trim() ?? ''
  if (!trimmed) return true

  const base = getWorkflowNodeLabel(nodeType)
  if (trimmed === base) return true

  const pattern = new RegExp(`^${escapeRegExp(base)}(?: (\\d+))?$`)
  return pattern.test(trimmed)
}

export function formatWorkflowNodeTypeLabel(
  nodeType: TestFlowNodeType,
  ordinal?: number,
): string {
  const base = getWorkflowNodeLabel(nodeType)
  return ordinal != null ? `${base} ${ordinal}` : base
}

/**
 * Assigns 1-based ordinals per node type when the same type appears more than once
 * in `orderedNodeIds`. Single instances get no ordinal.
 */
export function getWorkflowNodeTypeOrdinals(
  orderedNodeIds: string[],
  getNodeType: (nodeId: string) => TestFlowNodeType | undefined,
): Map<string, number | undefined> {
  const countsByType = new Map<TestFlowNodeType, number>()

  for (const id of orderedNodeIds) {
    const nodeType = getNodeType(id)
    if (!nodeType) continue
    countsByType.set(nodeType, (countsByType.get(nodeType) ?? 0) + 1)
  }

  const ordinals = new Map<string, number | undefined>()
  const nextIndexByType = new Map<TestFlowNodeType, number>()

  for (const id of orderedNodeIds) {
    const nodeType = getNodeType(id)
    if (!nodeType) {
      ordinals.set(id, undefined)
      continue
    }

    const total = countsByType.get(nodeType) ?? 1
    if (total <= 1) {
      ordinals.set(id, undefined)
      continue
    }

    const index = (nextIndexByType.get(nodeType) ?? 0) + 1
    nextIndexByType.set(nodeType, index)
    ordinals.set(id, index)
  }

  return ordinals
}

export function resolveWorkflowNodeDisplayLabel(
  nodeType: TestFlowNodeType,
  customLabel: string | undefined,
  ordinal?: number,
): string {
  const typeLabel = formatWorkflowNodeTypeLabel(nodeType, ordinal)
  if (isAutoGeneratedWorkflowLabel(customLabel, nodeType)) {
    return typeLabel
  }
  return customLabel?.trim() ?? typeLabel
}
