import type { TestFlowNodeType } from './types'

export type WorkflowNodeMeta = {
  type: TestFlowNodeType
  label: string
  description: string
}

export const WORKFLOW_NODE_META: WorkflowNodeMeta[] = [
  { type: 'start', label: 'Start', description: 'Flow entry point' },
  { type: 'end', label: 'End', description: 'Flow exit point' },
  { type: 'script', label: 'Script', description: 'Run custom code' },
  { type: 'api-call', label: 'API Call', description: 'HTTP request step' },
  { type: 'if-else', label: 'If / Else', description: 'Conditional branch' },
  { type: 'for-loop', label: 'For Loop', description: 'Iterate a fixed count' },
  { type: 'do-while', label: 'Do While', description: 'Loop until condition' },
  { type: 'wait', label: 'Wait', description: 'Pause execution' },
]

export const LOOP_BODY_WORK_NODE_TYPES: TestFlowNodeType[] = [
  'script',
  'api-call',
  'wait',
  'if-else',
  'for-loop',
  'do-while',
]

export const isLoopBodyWorkNodeType = (nodeType: TestFlowNodeType): boolean => {
  return LOOP_BODY_WORK_NODE_TYPES.includes(nodeType)
}

export const isTestFlowNodeType = (value: string): value is TestFlowNodeType => {
  return WORKFLOW_NODE_META.some((def) => def.type === value)
}

export const getWorkflowNodeLabel = (nodeType: TestFlowNodeType): string => {
  return WORKFLOW_NODE_META.find((def) => def.type === nodeType)?.label ?? nodeType
}

const escapeRegExp = (value: string): string => {
  return value.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')
}

export const isAutoGeneratedWorkflowLabel = (
  label: string | undefined,
  nodeType: TestFlowNodeType,
): boolean => {
  const trimmed = label?.trim() ?? ''
  if (!trimmed) return true

  const base = getWorkflowNodeLabel(nodeType)
  if (trimmed === base) return true

  const pattern = new RegExp(`^${escapeRegExp(base)}(?: (\\d+))?$`)
  return pattern.test(trimmed)
}

export const formatWorkflowNodeTypeLabel = (
  nodeType: TestFlowNodeType,
  ordinal?: number,
): string => {
  const base = getWorkflowNodeLabel(nodeType)
  return ordinal != null ? `${base} ${ordinal}` : base
}

export const getWorkflowNodeTypeOrdinals = (
  orderedNodeIds: string[],
  getNodeType: (nodeId: string) => TestFlowNodeType | undefined,
): Map<string, number | undefined> => {
  const countsByType = new Map<TestFlowNodeType, number>()

  for (const id of orderedNodeIds) {
    const nodeType = getNodeType(id)
    if (!nodeType) continue
    countsByType.set(nodeType, (countsByType.get(nodeType) ?? 0) + 1)
  }

  const ordinals = new Map<string, number | undefined>()
  const nextIndexByType = new Map<TestFlowNodeType, number>()

  for (const id of orderedNodeIds) {
    const nodeType = getNodeType(id)
    if (!nodeType) {
      ordinals.set(id, undefined)
      continue
    }

    const total = countsByType.get(nodeType) ?? 1
    if (total <= 1) {
      ordinals.set(id, undefined)
      continue
    }

    const index = (nextIndexByType.get(nodeType) ?? 0) + 1
    nextIndexByType.set(nodeType, index)
    ordinals.set(id, index)
  }

  return ordinals
}

export const resolveWorkflowNodeDisplayLabel = (
  nodeType: TestFlowNodeType,
  customLabel: string | undefined,
  ordinal?: number,
): string => {
  const typeLabel = formatWorkflowNodeTypeLabel(nodeType, ordinal)
  if (isAutoGeneratedWorkflowLabel(customLabel, nodeType)) {
    return typeLabel
  }
  return customLabel?.trim() ?? typeLabel
}
