DO $$
BEGIN
    IF NOT EXISTS (SELECT FROM pg_roles WHERE rolname = '__POSTGRES_APP_USER__') THEN
        CREATE USER __POSTGRES_APP_USER__ WITH 
            PASSWORD '__POSTGRES_APP_PASSWORD__'
            NOSUPERUSER 
            NOCREATEDB 
            NOCREATEROLE 
            NOREPLICATION;
    END IF;
END
$$;

GRANT CONNECT ON DATABASE __DB_NAME__ TO __POSTGRES_APP_USER__;

GRANT USAGE ON SCHEMA __DB_SCHEMA__ TO __POSTGRES_APP_USER__;

GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA __DB_SCHEMA__ TO __POSTGRES_APP_USER__;

GRANT USAGE ON ALL SEQUENCES IN SCHEMA __DB_SCHEMA__ TO __POSTGRES_APP_USER__;

GRANT EXECUTE ON ALL FUNCTIONS IN SCHEMA __DB_SCHEMA__ TO __POSTGRES_APP_USER__;

ALTER DEFAULT PRIVILEGES IN SCHEMA __DB_SCHEMA__
    GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO __POSTGRES_APP_USER__;

ALTER DEFAULT PRIVILEGES IN SCHEMA __DB_SCHEMA__
    GRANT USAGE ON SEQUENCES TO __POSTGRES_APP_USER__;

ALTER DEFAULT PRIVILEGES IN SCHEMA __DB_SCHEMA__
    GRANT EXECUTE ON FUNCTIONS TO __POSTGRES_APP_USER__;

REVOKE CREATE ON SCHEMA public FROM __POSTGRES_APP_USER__;

REVOKE ALL ON pg_catalog.pg_authid FROM __POSTGRES_APP_USER__;
REVOKE ALL ON pg_catalog.pg_auth_members FROM __POSTGRES_APP_USER__;