/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SplatRouteImport } from './routes/$'
import { Route as appRouteRouteImport } from './routes/(app)/route'
import { Route as appIndexRouteImport } from './routes/(app)/index'
import { Route as authLoginRouteImport } from './routes/(auth)/login'
import { Route as appUsersRouteImport } from './routes/(app)/users'
import { Route as appTestRunsRouteImport } from './routes/(app)/test-runs'
import { Route as appTestFlowCreateRouteImport } from './routes/(app)/test-flow-create'
import { Route as appTestFlowRouteImport } from './routes/(app)/test-flow'
import { Route as appSettingsRouteImport } from './routes/(app)/settings'
import { Route as appTestFlowIndexRouteImport } from './routes/(app)/test-flow/index'
import { Route as appTestFlowIdEditRouteImport } from './routes/(app)/test-flow/$id/edit'

const SplatRoute = SplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => rootRouteImport,
} as any)
const appRouteRoute = appRouteRouteImport.update({
  id: '/(app)',
  getParentRoute: () => rootRouteImport,
} as any)
const appIndexRoute = appIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => appRouteRoute,
} as any)
const authLoginRoute = authLoginRouteImport.update({
  id: '/(auth)/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const appUsersRoute = appUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => appRouteRoute,
} as any)
const appTestRunsRoute = appTestRunsRouteImport.update({
  id: '/test-runs',
  path: '/test-runs',
  getParentRoute: () => appRouteRoute,
} as any)
const appTestFlowCreateRoute = appTestFlowCreateRouteImport.update({
  id: '/test-flow-create',
  path: '/test-flow-create',
  getParentRoute: () => appRouteRoute,
} as any)
const appTestFlowRoute = appTestFlowRouteImport.update({
  id: '/test-flow',
  path: '/test-flow',
  getParentRoute: () => appRouteRoute,
} as any)
const appSettingsRoute = appSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => appRouteRoute,
} as any)
const appTestFlowIndexRoute = appTestFlowIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => appTestFlowRoute,
} as any)
const appTestFlowIdEditRoute = appTestFlowIdEditRouteImport.update({
  id: '/$id/edit',
  path: '/$id/edit',
  getParentRoute: () => appTestFlowRoute,
} as any)

export interface FileRoutesByFullPath {
  '/$': typeof SplatRoute
  '/settings': typeof appSettingsRoute
  '/test-flow': typeof appTestFlowRouteWithChildren
  '/test-flow-create': typeof appTestFlowCreateRoute
  '/test-runs': typeof appTestRunsRoute
  '/users': typeof appUsersRoute
  '/login': typeof authLoginRoute
  '/': typeof appIndexRoute
  '/test-flow/': typeof appTestFlowIndexRoute
  '/test-flow/$id/edit': typeof appTestFlowIdEditRoute
}
export interface FileRoutesByTo {
  '/$': typeof SplatRoute
  '/settings': typeof appSettingsRoute
  '/test-flow-create': typeof appTestFlowCreateRoute
  '/test-runs': typeof appTestRunsRoute
  '/users': typeof appUsersRoute
  '/login': typeof authLoginRoute
  '/': typeof appIndexRoute
  '/test-flow': typeof appTestFlowIndexRoute
  '/test-flow/$id/edit': typeof appTestFlowIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/(app)': typeof appRouteRouteWithChildren
  '/$': typeof SplatRoute
  '/(app)/settings': typeof appSettingsRoute
  '/(app)/test-flow': typeof appTestFlowRouteWithChildren
  '/(app)/test-flow-create': typeof appTestFlowCreateRoute
  '/(app)/test-runs': typeof appTestRunsRoute
  '/(app)/users': typeof appUsersRoute
  '/(auth)/login': typeof authLoginRoute
  '/(app)/': typeof appIndexRoute
  '/(app)/test-flow/': typeof appTestFlowIndexRoute
  '/(app)/test-flow/$id/edit': typeof appTestFlowIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/$'
    | '/settings'
    | '/test-flow'
    | '/test-flow-create'
    | '/test-runs'
    | '/users'
    | '/login'
    | '/'
    | '/test-flow/'
    | '/test-flow/$id/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/$'
    | '/settings'
    | '/test-flow-create'
    | '/test-runs'
    | '/users'
    | '/login'
    | '/'
    | '/test-flow'
    | '/test-flow/$id/edit'
  id:
    | '__root__'
    | '/(app)'
    | '/$'
    | '/(app)/settings'
    | '/(app)/test-flow'
    | '/(app)/test-flow-create'
    | '/(app)/test-runs'
    | '/(app)/users'
    | '/(auth)/login'
    | '/(app)/'
    | '/(app)/test-flow/'
    | '/(app)/test-flow/$id/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  appRouteRoute: typeof appRouteRouteWithChildren
  SplatRoute: typeof SplatRoute
  authLoginRoute: typeof authLoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/$': {
      id: '/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(app)': {
      id: '/(app)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof appRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(app)/': {
      id: '/(app)/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof appIndexRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/(auth)/login': {
      id: '/(auth)/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof authLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(app)/users': {
      id: '/(app)/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof appUsersRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/(app)/test-runs': {
      id: '/(app)/test-runs'
      path: '/test-runs'
      fullPath: '/test-runs'
      preLoaderRoute: typeof appTestRunsRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/(app)/test-flow-create': {
      id: '/(app)/test-flow-create'
      path: '/test-flow-create'
      fullPath: '/test-flow-create'
      preLoaderRoute: typeof appTestFlowCreateRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/(app)/test-flow': {
      id: '/(app)/test-flow'
      path: '/test-flow'
      fullPath: '/test-flow'
      preLoaderRoute: typeof appTestFlowRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/(app)/settings': {
      id: '/(app)/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof appSettingsRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/(app)/test-flow/': {
      id: '/(app)/test-flow/'
      path: '/'
      fullPath: '/test-flow/'
      preLoaderRoute: typeof appTestFlowIndexRouteImport
      parentRoute: typeof appTestFlowRoute
    }
    '/(app)/test-flow/$id/edit': {
      id: '/(app)/test-flow/$id/edit'
      path: '/$id/edit'
      fullPath: '/test-flow/$id/edit'
      preLoaderRoute: typeof appTestFlowIdEditRouteImport
      parentRoute: typeof appTestFlowRoute
    }
  }
}

interface appTestFlowRouteChildren {
  appTestFlowIndexRoute: typeof appTestFlowIndexRoute
  appTestFlowIdEditRoute: typeof appTestFlowIdEditRoute
}

const appTestFlowRouteChildren: appTestFlowRouteChildren = {
  appTestFlowIndexRoute: appTestFlowIndexRoute,
  appTestFlowIdEditRoute: appTestFlowIdEditRoute,
}

const appTestFlowRouteWithChildren = appTestFlowRoute._addFileChildren(
  appTestFlowRouteChildren,
)

interface appRouteRouteChildren {
  appSettingsRoute: typeof appSettingsRoute
  appTestFlowRoute: typeof appTestFlowRouteWithChildren
  appTestFlowCreateRoute: typeof appTestFlowCreateRoute
  appTestRunsRoute: typeof appTestRunsRoute
  appUsersRoute: typeof appUsersRoute
  appIndexRoute: typeof appIndexRoute
}

const appRouteRouteChildren: appRouteRouteChildren = {
  appSettingsRoute: appSettingsRoute,
  appTestFlowRoute: appTestFlowRouteWithChildren,
  appTestFlowCreateRoute: appTestFlowCreateRoute,
  appTestRunsRoute: appTestRunsRoute,
  appUsersRoute: appUsersRoute,
  appIndexRoute: appIndexRoute,
}

const appRouteRouteWithChildren = appRouteRoute._addFileChildren(
  appRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  appRouteRoute: appRouteRouteWithChildren,
  SplatRoute: SplatRoute,
  authLoginRoute: authLoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
