BEGIN;

    CREATE SEQUENCE IF NOT EXISTS haqa_schema.users_id_seq INCREMENT BY 1 START WITH 1 MINVALUE 1 NO MAXVALUE;
    CREATE SEQUENCE IF NOT EXISTS haqa_schema.roles_id_seq INCREMENT BY 1 START WITH 1 MINVALUE 1 NO MAXVALUE;
    CREATE SEQUENCE IF NOT EXISTS haqa_schema.functions_id_seq INCREMENT BY 1 START WITH 1 MINVALUE 1 NO MAXVALUE;

COMMIT;